<?php

namespace Dinamica\MedAlfa\MedAlfaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EstudiosProfesionalesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstudiosProfesionalesRepository extends EntityRepository
{
}